# Create a dockerfile with go image

# Create a directory to hold the application code inside the image, this will be the working directory for your application

# Set the working directory to /usr/src/app

# Copy go.* and main.go to the working directory

# run go install

# Copy the current directory contents into the container at /usr/src/app

# Make port 3000 available to the world outside this container

# Run main.go when the container launches

# Write a docker command to build the image and tag it as mygoapp
