# Create a dockerfile with node image

# Create a directory to hold the application code inside the image, this will be the working directory for your application

# Set the working directory to /usr/src/app

# Install python 

# Copy the current directory contents into the container at /usr/src/app

# Make port 3000 available to the world outside this container

# Run server.py when the container launches

# Write a docker comnand to build the image and tag it as mypythonapp
